### ISSUE TITLE
Error occurring in installing paper-doll

### ISSUE THREAD

**Issue by kboby91** [kyamagu/matlab-bdb#2]
Hi, i wanna parse an image using your project paper-doll parsing.
I'm having trouble compiling matlab-bdb in paper-doll parsing on ubunto 14.04 and matlab 2014a
this is the error

```
/tmp/mex_13959721201434_19551/libbdbmex.o: In function `bdbmex::Record::deserialize_mxarray(std::vector<unsigned char,
std::allocator<unsigned char> > const&, mxArray_tag**)':
libbdbmex.cc:(.text+0x1f9): undefined reference to `mxDeserialize'
/tmp/mex_13959721201434_19551/libbdbmex.o: In function `bdbmex::Record::decompress_mxarray(std::vector<unsigned char,
std::allocator<unsigned char> > const&, mxArray_tag**)':
libbdbmex.cc:(.text+0x2b6): undefined reference to `mxDeserialize'
/tmp/mex_13959721201434_19551/libbdbmex.o: In function `bdbmex::Record::serialize_mxarray(mxArray_tag const*,
std::vector<unsigned char, std::allocator<unsigned char> >*)':
libbdbmex.cc:(.text+0x95a): undefined reference to `mxSerialize'
/tmp/mex_13959721201434_19551/libbdbmex.o: In function `bdbmex::Record::compress_mxarray(mxArray_tag const*,
std::vector<unsigned char, std::allocator<unsigned char> >*)':
libbdbmex.cc:(.text+0xdbe): undefined reference to `mxSerialize'
collect2: error: ld returned 1 exit status
```

I need a help...

**Comment by kyamagu** [comment]
@kboby91 LL14-34 of `src/libbdbmex.cc` define these definitions to undocumented MEX functions. [You might need to remove the namespace hacks](http://undocumentedmatlab.com/blog/serializing-deserializing-matlab-data), depending on the Matlab version.

**Comment by kboby91** [comment]
Thanks a lot. I appreciate your help. It works

**Comment by rikenmehta03** [comment]
can you guide me through the process of removing these namespace hacks. I am also facing same problem. I am totally new to matlab.

**Comment by kyamagu** [comment]
@rikenmehta03 You can replace `lib/matlab-bdb` directory with the latest commit of this git repository. That is, remove the old `lib/matlab-bdb` directory, download and extract [a zip archive](https://github.com/kyamagu/matlab-bdb/archive/master.zip), and rename the extracted directory to `matlab-bdb` inside `lib/` dir. Once done, compile the package by `bdb.make` command inside matlab.

The necessary change is the following.

[bdb-patch.txt](https://github.com/kyamagu/matlab-bdb/files/76792/bdb-patch.txt)
