### ISSUE TITLE
Error occurring in building paper-doll

### ISSUE THREAD

**Issue by scgy0009** [kyamagu/matlab-bdb#3]
Hi, i wanna parse an image using your project paper-doll parsing.
I'm having trouble compiling GCO_BuildLib in paper-doll parsing on ubuntu 14.04 and matlab 2015a
this is the error info:

> In GCO_BuildLib (line 67) 
> Warning: You are using gcc version '4.8.4-2ubuntu1~14.04)'. The version of gcc is not supported. The version currently
> supported with MEX is '4.7.x'. For a list of currently supported compilers see:
> http://www.mathworks.com/support/compilers/current_release. 
> In GCO_BuildLib (line 67) 
> Error using mex
> /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:31:23: warning: ‘GCO_CLOCKS_PER_SEC’
> initialized and declared ‘extern’ [enabled by default]
>  extern "C" gcoclock_t GCO_CLOCKS_PER_SEC = CLOCKS_PER_SEC;

```
                   ^
```

In file included from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.h:109:0,
                 from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:4:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h: In instantiation of ‘int Energy<captype, tcaptype,
flowtype>::get_var(Energy<captype, tcaptype, flowtype>::Var) [with captype = int; tcaptype = int; flowtype = long long int;
Energy<captype, tcaptype, flowtype>::Var = int]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:197:20:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:328:91: error: ‘what_segment’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
 inline int Energy<captype,tcaptype,flowtype>::get_var(Var x) { return (int) what_segment(x); }

```
                                                                                       ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:328:91: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:328:91: note: use ‘this->what_segment’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h: In instantiation of ‘void Energy<captype, tcaptype,
flowtype>::add_term1(Energy<captype, tcaptype, flowtype>::Var, Energy<captype, tcaptype, flowtype>::Value, Energy<captype,
tcaptype, flowtype>::Value) [with captype = int; tcaptype = int; flowtype = long long int; Energy<captype, tcaptype,
flowtype>::Var = int; Energy<captype, tcaptype, flowtype>::Value = int]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:280:22:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:207:22: error: ‘add_tweights’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  add_tweights(x, B, A);

```
                  ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:207:22: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:207:22: note: use ‘this->add_tweights’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h: In instantiation of ‘void Energy<captype, tcaptype,
flowtype>::add_term2(Energy<captype, tcaptype, flowtype>::Var, Energy<captype, tcaptype, flowtype>::Var, Energy<captype,
tcaptype, flowtype>::Value, Energy<captype, tcaptype, flowtype>::Value, Energy<captype, tcaptype, flowtype>::Value,
Energy<captype, tcaptype, flowtype>::Value) [with captype = int; tcaptype = int; flowtype = long long int; Energy<captype,
tcaptype, flowtype>::Var = int; Energy<captype, tcaptype, flowtype>::Value = int]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:304:42:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:220:22: error: ‘add_tweights’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
  add_tweights(x, D, A);

```
                  ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:220:22: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:220:22: note: use ‘this->add_tweights’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:235:23: error: ‘add_tweights’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_tweights(x, 0, B); /\* first term */

```
                   ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:235:23: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:235:23: note: use ‘this->add_tweights’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:236:24: error: ‘add_tweights’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_tweights(y, 0, -B); /\* second term */

```
                    ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:236:24: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:236:24: note: use ‘this->add_tweights’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:237:24: error: ‘add_edge’ was not declared in this scope,
and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_edge(x, y, 0, B+C); /\* third term */

```
                    ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:237:24: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:237:24: note: use ‘this->add_edge’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:245:24: error: ‘add_tweights’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_tweights(x, 0, -C); /\* first term */

```
                    ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:245:24: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:245:24: note: use ‘this->add_tweights’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:246:23: error: ‘add_tweights’ was not declared in this
scope, and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_tweights(y, 0, C); /\* second term */

```
                   ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:246:23: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:246:23: note: use ‘this->add_tweights’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:247:24: error: ‘add_edge’ was not declared in this scope,
and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_edge(x, y, B+C, 0); /\* third term */

```
                    ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:247:24: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:247:24: note: use ‘this->add_edge’ instead
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:251:22: error: ‘add_edge’ was not declared in this scope,
and no declarations were found by argument-dependent lookup at the point of instantiation [-fpermissive]
   add_edge(x, y, B, C);

```
                  ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:251:22: note: declarations in dependent base ‘Graph<int,
int, long long int>’ are not found by unqualified lookup
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:251:22: note: use ‘this->add_edge’ instead
In file included from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.h:110:0,
                 from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:4:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/graph.cpp: In instantiation of ‘Graph<captype, tcaptype,
flowtype>::Graph(int, int, void (_)(char_)) [with captype = int; tcaptype = int; flowtype = long long int]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:187:189:   required from ‘Energy<captype, tcaptype,
flowtype>::Energy(int, int, void (_)(char_)) [with captype = int; tcaptype = int; flowtype = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:1230:33:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/graph.cpp:21:83: warning: deprecated conversion from string constant
to ‘char_’ [-Wwrite-strings]
  if (!nodes || !arcs) { if (error_function) (_error_function)("Not enough memory!"); exit(1); }

```
                                                                               ^
```

In file included from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.h:111:0,
                 from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:4:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp: In instantiation of ‘flowtype Graph<captype, tcaptype,
flowtype>::maxflow(bool, Block<int>_) [with captype = int; tcaptype = int; flowtype = long long int]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:325:33:   required from ‘Energy<captype, tcaptype,
flowtype>::TotalValue Energy<captype, tcaptype, flowtype>::minimize() [with captype = int; tcaptype = int; flowtype = long
long int; Energy<captype, tcaptype, flowtype>::TotalValue = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:1237:37:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:484:145: warning: deprecated conversion from string
constant to ‘char_’ [-Wwrite-strings]
  if (maxflow_iteration == 0 && reuse_trees) { if (error_function) (*error_function)("reuse_trees cannot be used in the first
  call to maxflow()!"); exit(1); }

```
                                                                                                                                             ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:485:126: warning: deprecated conversion from string
constant to ‘char_’ [-Wwrite-strings]
  if (changed_list && !reuse_trees) { if (error_function) (_error_function)("changed_list cannot be used without
  reuse_trees!"); exit(1); }

```
                                                                                                                          ^
                                                                                                                          In
                                                                                                                          file
                                                                                                                          included
                                                                                                                          from
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.h:110:0,

                                                                                                                          from
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:4:
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/graph.cpp:
                                                                                                                          In
                                                                                                                          instantiation
                                                                                                                          of
                                                                                                                          ‘void
                                                                                                                          Graph<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::reallocate_nodes(int)
                                                                                                                          [with
                                                                                                                          captype
                                                                                                                          =
                                                                                                                          int;
                                                                                                                          tcaptype
                                                                                                                          =
                                                                                                                          int;
                                                                                                                          flowtype
                                                                                                                          =
                                                                                                                          long
                                                                                                                          long
                                                                                                                          int]’:
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/graph.h:364:54:
                                                                                                                          required
                                                                                                                          from
                                                                                                                          ‘Graph<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::node_id
                                                                                                                          Graph<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::add_node(int)
                                                                                                                          [with
                                                                                                                          captype
                                                                                                                          =
                                                                                                                          int;
                                                                                                                          tcaptype
                                                                                                                          =
                                                                                                                          int;
                                                                                                                          flowtype
                                                                                                                          =
                                                                                                                          long
                                                                                                                          long
                                                                                                                          int;
                                                                                                                          Graph<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::node_id
                                                                                                                          =
                                                                                                                          int]’
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:198:30:
                                                                                                                          required
                                                                                                                          from
                                                                                                                          ‘Energy<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::Var
                                                                                                                          Energy<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::add_variable(int)
                                                                                                                          [with
                                                                                                                          captype
                                                                                                                          =
                                                                                                                          int;
                                                                                                                          tcaptype
                                                                                                                          =
                                                                                                                          int;
                                                                                                                          flowtype
                                                                                                                          =
                                                                                                                          long
                                                                                                                          long
                                                                                                                          int;
                                                                                                                          Energy<captype,
                                                                                                                          tcaptype,
                                                                                                                          flowtype>::Var
                                                                                                                          =
                                                                                                                          int]’
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:1140:31:
                                                                                                                          required
                                                                                                                          from
                                                                                                                          here
                                                                                                                          /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/graph.cpp:70:74:
                                                                                                                          warning:
                                                                                                                          deprecated
                                                                                                                          conversion
                                                                                                                          from
                                                                                                                          string
                                                                                                                          constant
                                                                                                                          to
                                                                                                                          ‘char*’
                                                                                                                          [-Wwrite-strings]

                                                                                                                          if
                                                                                                                          (!nodes)
                                                                                                                          {
                                                                                                                          if
                                                                                                                          (error_function)
                                                                                                                          (*error_function)("Not
                                                                                                                          enough
                                                                                                                          memory!");
                                                                                                                          exit(1);
                                                                                                                          }

                                                                      ^
```

In file included from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/graph.h:43:0,
                 from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:77,
                 from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.h:109,
                 from /home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:4:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/block.h: In instantiation of ‘Type\* Block<Type>::New(int) [with
Type = int]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:110:36:   required from ‘void Graph<captype, tcaptype,
flowtype>::add_to_changed_list(Graph<captype, tcaptype, flowtype>::node_) [with captype = int; tcaptype = int; flowtype = long
long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:520:27:   required from ‘flowtype Graph<captype,
tcaptype, flowtype>::maxflow(bool, Block<int>_) [with captype = int; tcaptype = int; flowtype = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:325:33:   required from ‘Energy<captype, tcaptype,
flowtype>::TotalValue Energy<captype, tcaptype, flowtype>::minimize() [with captype = int; tcaptype = int; flowtype = long
long int; Energy<captype, tcaptype, flowtype>::TotalValue = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:1237:37:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/block.h:124:76: warning: deprecated conversion from string constant
to ‘char_’ [-Wwrite-strings]
     if (!next) { if (error_function) (_error_function)("Not enough memory!"); exit(1); }

```
                                                                        ^
```

/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/block.h: In instantiation of ‘Type\* DBlock<Type>::New() [with Type
= Graph<int, int, long long int>::nodeptr]’:
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:95:5:   required from ‘void Graph<captype, tcaptype,
flowtype>::set_orphan_rear(Graph<captype, tcaptype, flowtype>::node_) [with captype = int; tcaptype = int; flowtype = long
long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:183:36:   required from ‘void Graph<captype, tcaptype,
flowtype>::maxflow_reuse_trees_init() [with captype = int; tcaptype = int; flowtype = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/maxflow.cpp:487:44:   required from ‘flowtype Graph<captype,
tcaptype, flowtype>::maxflow(bool, Block<int>_) [with captype = int; tcaptype = int; flowtype = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/energy.h:325:33:   required from ‘Energy<captype, tcaptype,
flowtype>::TotalValue Energy<captype, tcaptype, flowtype>::minimize() [with captype = int; tcaptype = int; flowtype = long
long int; Energy<captype, tcaptype, flowtype>::TotalValue = long long int]’
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/GCoptimization.cpp:1237:37:   required from here
/home/boajianmin/research/paperdoll-v1.0/lib/gco-v3.0/src/block.h:223:76: warning: deprecated conversion from string constant
to ‘char_’ [-Wwrite-strings]
    if (!first) { if (error_function) (_error_function)("Not enough memory!"); exit(1); }

Error in GCO_BuildLib (line 67)
eval(mexcmd);  % compile and link in one step

**Comment by kyamagu** [comment]
@scgy0009 This is completely unrelated to `matlab-bdb`, but I can give you a patch for this specific problem.

[gco-patch.txt](https://github.com/kyamagu/matlab-bdb/files/79335/gco-patch.txt)

**Comment by scgy0009** [comment]
thanks for your answer. actually, this is completely unrelated to matlab-bdb, but I didn't found your project paperdoll on the github. So I came here to ask the issue. thanks for your answer, but I can't understand you gco-patch.txt, what does it mean? what should I do to fix the problem? Sorry to bother you again.

**Comment by kyamagu** [comment]
@scgy0009 This is [a patch file](https://en.wikipedia.org/wiki/Patch_%28Unix%29). Use like the following.

```
patch -p1 < gco-patch.txt
```

**Comment by scgy0009** [comment]
thanks! it works.
